/**
 * AI Actions Usage Example
 * 
 * This demonstrates how the AI assistant now controls the portfolio
 */

// Example 1: User asks about a project
// ======================================
const userMessage1 = "Tell me about Brave Up";

// AI Response (generated by LLM):
const aiResponse1 = `Brave Up! is my mental health support platform for entrepreneurs.
It helps founders manage stress and burnout through personalized support.
Let me show you the project details.
ACTION: {"type": "navigate", "target": "braveup"}`;

// What happens:
// 1. User sees: "Brave Up! is my mental health support platform..."
// 2. After 500ms: Navigates to /projects/braveup
// 3. User is now viewing the Brave Up project page

// Example 2: User wants to see skills
// ======================================
const userMessage2 = "What technologies do you know?";

const aiResponse2 = `I have expertise in React, TypeScript, Node.js, Python, and many more technologies.
Let me show you my complete tech stack.
ACTION: {"type": "scrollToSection", "section": "expertise"}
ACTION: {"type": "highlight", "target": "expertise"}`;

// What happens:
// 1. User sees: "I have expertise in React, TypeScript..."
// 2. Scrolls smoothly to expertise section
// 3. Section glows with cyan animation for 3 seconds
// 4. User's attention is drawn to the expertise section

// Example 3: User wants the resume
// ======================================
const userMessage3 = "Can I download your CV?";

const aiResponse3 = `Of course! I'll download my resume for you right now.
ACTION: {"type": "downloadResume", "language": "en"}`;

// What happens:
// 1. User sees: "Of course! I'll download my resume..."
// 2. Resume_EN.pdf automatically downloads
// 3. User has the resume file

// Example 4: Complex interaction
// ======================================
const userMessage4 = "Show me your projects and give me your resume";

const aiResponse4 = `I'd be happy to show you my projects and provide my resume.
I've built several full-stack applications including Brave Up!, Deal Advisor, and more.
ACTION: {"type": "scrollToSection", "section": "projects"}
ACTION: {"type": "downloadResume", "language": "en"}`;

// What happens:
// 1. User sees the full text response
// 2. Scrolls to projects section
// 3. After 300ms delay: Resume downloads
// 4. User is viewing projects with resume downloaded

// Example 5: Opening modal
// ======================================
const userMessage5 = "Tell me more about Deal Advisor";

const aiResponse5 = `Deal Advisor is a comprehensive real estate analysis platform with AI-powered insights.
Let me open the detailed project view for you.
ACTION: {"type": "openModal", "modalType": "project", "data": {"id": "deal-advisor"}}`;

// What happens:
// 1. User sees the text description
// 2. Project modal opens with Deal Advisor details
// 3. User can explore project images, tech stack, links

// ============================================
// Behind the Scenes: Action Flow
// ============================================

/*
1. User sends message via useConversation hook
   ↓
2. ConversationManager.processMessage()
   ↓
3. AI Provider generates response (text + actions)
   ↓
4. ActionParser.parseResponse() extracts:
   - text: "Brave Up! is my mental health..."
   - actions: [{ type: "navigate", target: "braveup" }]
   ↓
5. Response displayed to user with typing animation
   ↓
6. After typing completes + 500ms delay
   ↓
7. useActionHandler.executeActions() runs
   ↓
8. Navigation/scroll/highlight/modal/download happens
   ↓
9. User sees the result of the action
*/

// ============================================
// Supported Actions
// ============================================

const actions = {
  // Navigate to pages/sections
  navigate: {
    type: 'navigate',
    target: 'projects' // or: home, ventures, contact, braveup, deal-advisor, etc.
  },
  
  // Scroll to section
  scrollToSection: {
    type: 'scrollToSection',
    section: 'expertise', // or: hero, projects, ventures, contact
    smooth: true
  },
  
  // Highlight element
  highlight: {
    type: 'highlight',
    target: 'expertise', // element ID or selector
    duration: 3000 // milliseconds
  },
  
  // Open modal
  openModal: {
    type: 'openModal',
    modalType: 'project', // or: contact, resume, image
    data: { id: 'braveup' } // modal-specific data
  },
  
  // Download resume
  downloadResume: {
    type: 'downloadResume',
    language: 'en' // or: 'es'
  }
};

// ============================================
// Action Validation
// ============================================

// ✅ Valid actions are executed
ActionParser.parseAction('{"type": "navigate", "target": "projects"}');
// Result: { type: 'navigate', target: 'projects' }

// ❌ Invalid actions are filtered out (logged but not executed)
ActionParser.parseAction('{"type": "invalid", "target": "nowhere"}');
// Result: null (logged warning)

// ❌ Invalid targets are rejected
ActionParser.parseAction('{"type": "navigate", "target": "nonexistent"}');
// Result: null (logged warning)

// ============================================
// Integration with UI Components
// ============================================

// In your component:
import { useActionHandler } from '@/features/ai-assistant/conversation/hooks';

function MyComponent() {
  const { executeAction } = useActionHandler();
  
  // Manually trigger an action
  const handleClick = async () => {
    await executeAction({
      type: 'navigate',
      target: 'projects'
    });
  };
  
  return <button onClick={handleClick}>Go to Projects</button>;
}

// Listen to modal events:
useEffect(() => {
  const handleModalOpen = (event) => {
    const { modalType, data } = event.detail;
    // Open your modal
    openModal(modalType, data);
  };
  
  window.addEventListener('ai-open-modal', handleModalOpen);
  return () => window.removeEventListener('ai-open-modal', handleModalOpen);
}, []);

// ============================================
// Summary
// ============================================

/*
The AI assistant is now a portfolio controller!

Before:
  User: "Tell me about Brave Up"
  AI: "Brave Up is a mental health platform..."
  User: [manually navigates to project]

After:
  User: "Tell me about Brave Up"
  AI: "Brave Up is a mental health platform..."
  AI: [automatically navigates to project]
  User: [viewing the project]

The assistant can now:
✅ Navigate between pages
✅ Scroll to specific sections
✅ Highlight important content
✅ Open detailed modals
✅ Download resume
✅ Combine multiple actions

All while maintaining a conversational, helpful tone!
*/

export default {
  actions,
  examples: [
    aiResponse1,
    aiResponse2,
    aiResponse3,
    aiResponse4,
    aiResponse5
  ]
};
