name: github actions hello world

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/hello-world-javascript-action@main
      with:
        who-to-greet: 'Mona the Octocat'
